name: Blockchain CI

on:
  push:
    paths:
      - 'blockchain/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: blockchain

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Inject secrets into environment
        run: |
          echo "SEPOLIA_URL=${{ secrets.SEPOLIA_URL }}" >> $GITHUB_ENV
          echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Compile smart contracts
        run: npx hardhat compile

      - name: Deploy to Sepolia
        run: npx hardhat run scripts/deploy.js --network sepolia

